---
version: '3.6'

services:

  node:
    image: node
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    command: npm start
    working_dir: /home/node/app
    user: node

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.6
    # image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: secret

volumes:
  data:
